# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftExample' do
  pod 'PoyntLib', :path => '../../PoyntLib.podspec'
  pod 'Bugsnag'
  pod 'KSCrash'
  pod 'OpenSSL-Universal'
end
