// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import Foundation;
@import ObjectiveC;
@import Foundation.NSURLSession;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

@interface NSData (SWIFT_EXTENSION(PoyntLib))
@end


SWIFT_CLASS("_TtC8PoyntLib15PoyntCardObject")
@interface PoyntCardObject : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8PoyntLib10PoyntDebug")
@interface PoyntDebug : NSObject
+ (PoyntDebug * _Nonnull)sharedDebugger;
@property (nonatomic) BOOL verbose;
+ (void)log:(NSString * _Nonnull)message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8PoyntLib19PoyntDiscountObject")
@interface PoyntDiscountObject : NSObject
@property (nonatomic) NSInteger amount;
@property (nonatomic, copy) NSString * _Nullable customName;
- (nonnull instancetype)initWithAmount:(NSInteger)amount customName:(NSString * _Nullable)customName OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8PoyntLib18PoyntFundingSource")
@interface PoyntFundingSource : NSObject
@property (nonatomic, strong) PoyntCardObject * _Nullable card;
@property (nonatomic, copy) NSString * _Nullable accountType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PoyntOrderItemTax;

SWIFT_CLASS("_TtC8PoyntLib20PoyntOrderItemObject")
@interface PoyntOrderItemObject : NSObject
@property (nonatomic, copy) NSString * _Nullable sku;
@property (nonatomic, copy) NSString * _Nullable clientNotes;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) NSInteger unitPrice;
@property (nonatomic, copy) NSArray<PoyntOrderItemTax *> * _Nullable taxes;
@property (nonatomic, copy) NSArray<PoyntDiscountObject *> * _Nullable discounts;
@property (nonatomic) float quantity;
@property (nonatomic, readonly) NSInteger tax;
@end


SWIFT_CLASS("_TtC8PoyntLib17PoyntOrderItemTax")
@interface PoyntOrderItemTax : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic) NSInteger amount;
- (nonnull instancetype)initWithAmount:(NSInteger)amount type:(NSString * _Nullable)type OBJC_DESIGNATED_INITIALIZER;
@end

@class PoyntPaymentAmountObject;

SWIFT_CLASS("_TtC8PoyntLib16PoyntOrderObject")
@interface PoyntOrderObject : NSObject
@property (nonatomic, copy) NSString * _Nullable notes;
@property (nonatomic, copy) NSString * _Nullable orderNumber;
@property (nonatomic, strong) PoyntPaymentAmountObject * _Nullable amounts;
@property (nonatomic, copy) NSArray<PoyntDiscountObject *> * _Nullable discounts;
@property (nonatomic, copy) NSArray<PoyntOrderItemObject *> * _Nullable items;
@property (nonatomic, copy) NSString * _Nullable orderId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSError;
@class PoyntTransactionResponseObject;
@class PoyntPaymentObject;
@class PoyntTransactionObject;
@class NSString;
@class NSURLSession;
@class NSURLSessionTask;

SWIFT_CLASS("_TtC8PoyntLib25PoyntPOSConnectionManager")
@interface PoyntPOSConnectionManager : NSObject <NSURLSessionTaskDelegate, NSURLSessionDelegate>
@property (nonatomic, copy) void (^ _Nullable onError)(NSError * _Nonnull error);
@property (nonatomic, copy) void (^ _Nullable onTransactionResponse)(PoyntTransactionResponseObject * _Nonnull data, NSInteger type);
@property (nonatomic, copy) NSString * _Nullable url;
@property (nonatomic, copy) NSString * _Nonnull pairingCode;
@property (nonatomic, copy) NSString * _Nonnull clientName;
@property (nonatomic) NSInteger timeout;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)authorizeSales:(PoyntPaymentObject * _Nonnull)paymentObject;
- (void)authorizeVoidPreSales:(PoyntTransactionObject * _Nonnull)transaction;
- (void)authorizeVoid:(PoyntTransactionObject * _Nonnull)transaction;
- (void)authorizeRefund:(PoyntTransactionObject * _Nonnull)transaction;
- (void)authorizePreSales:(PoyntPaymentObject * _Nonnull)paymentObject;
- (void)authorizePairing:(NSString * _Nonnull)code;
- (void)authorizeCapture:(PoyntTransactionObject * _Nonnull)transaction;
- (void)URLSessionDidFinishEventsForBackgroundURLSession:(NSURLSession * _Nonnull)session;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
- (void)URLSession:(NSURLSession * _Nonnull)session didBecomeInvalidWithError:(NSError * _Nullable)error;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didSendBodyData:(int64_t)bytesSent totalBytesSent:(int64_t)totalBytesSent totalBytesExpectedToSend:(int64_t)totalBytesExpectedToSend;
@end


SWIFT_CLASS("_TtC8PoyntLib24PoyntPaymentAmountObject")
@interface PoyntPaymentAmountObject : NSObject
@property (nonatomic) NSInteger subTotal;
@property (nonatomic) NSInteger discountTotal;
@property (nonatomic) NSInteger taxTotal;
@property (nonatomic, copy) NSString * _Nullable currency;
- (nonnull instancetype)initWithOrder:(PoyntOrderObject * _Nonnull)order OBJC_DESIGNATED_INITIALIZER;
- (void)calculate:(PoyntOrderObject * _Nonnull)order;
@end


SWIFT_CLASS("_TtC8PoyntLib18PoyntPaymentObject")
@interface PoyntPaymentObject : NSObject
@property (nonatomic, copy) NSString * _Nonnull referenceId;
@property (nonatomic) NSInteger amount;
@property (nonatomic) NSInteger tipAmount;
@property (nonatomic, strong) PoyntPaymentAmountObject * _Nullable amounts;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, copy) NSString * _Nullable orderId;
@property (nonatomic, strong) PoyntOrderObject * _Nullable order;
@property (nonatomic, copy) NSArray<PoyntTransactionObject *> * _Nullable transactions;
- (void)update;
@property (nonatomic, readonly) NSInteger absoluteDiscountTotal;
@property (nonatomic, readonly) NSInteger absoulteTaxTotal;
@property (nonatomic, readonly) NSInteger absoluteTotal;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNetService;
@class NSURL;

SWIFT_CLASS("_TtC8PoyntLib13PoyntTerminal")
@interface PoyntTerminal : NSObject
@property (nonatomic, strong) NSNetService * _Nullable service;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable ip;
@property (nonatomic, strong) NSURL * _Nullable url;
@end

@class NSNetServiceBrowser;
@class NSNumber;

SWIFT_CLASS("_TtC8PoyntLib21PoyntTerminalDiscover")
@interface PoyntTerminalDiscover : NSObject <NSNetServiceBrowserDelegate, NSNetServiceDelegate>
- (void)findTerminals:(void (^ _Nonnull)(NSArray<PoyntTerminal *> * _Nonnull terminals))complete;
- (void)netServiceBrowser:(NSNetServiceBrowser * _Nonnull)aNetServiceBrowser didFindService:(NSNetService * _Nonnull)aNetService moreComing:(BOOL)moreComing;
- (void)netServiceBrowser:(NSNetServiceBrowser * _Nonnull)aNetServiceBrowser didRemoveService:(NSNetService * _Nonnull)aNetService moreComing:(BOOL)moreComing;
- (void)netServiceDidResolveAddress:(NSNetService * _Nonnull)sender;
- (void)netService:(NSNetService * _Nonnull)sender didNotResolve:(NSDictionary<NSString *, NSNumber *> * _Nonnull)errorDict;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8PoyntLib23PoyntTransactionAmounts")
@interface PoyntTransactionAmounts : NSObject
@property (nonatomic) NSInteger orderAmount;
@property (nonatomic) NSInteger tipAmount;
@property (nonatomic) NSInteger cashbackAmount;
@property (nonatomic, copy) NSString * _Nonnull currency;
- (nonnull instancetype)initWithOrderAmount:(NSInteger)orderAmount tipAmount:(NSInteger)tipAmount cashbackAmount:(NSInteger)cashbackAmount OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) NSInteger transactionAmount;
@end


SWIFT_CLASS("_TtC8PoyntLib22PoyntTransactionObject")
@interface PoyntTransactionObject : NSObject
@property (nonatomic, copy) NSString * _Nonnull poyntRequestId;
@property (nonatomic, copy) NSString * _Nullable transactionId;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable action;
@property (nonatomic, strong) PoyntTransactionAmounts * _Nullable amounts;
@property (nonatomic, strong) PoyntFundingSource * _Nullable fundingSource;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull context;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nonnull references;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable parentId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithData:(NSDictionary<NSString *, id> * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8PoyntLib30PoyntTransactionResponseObject")
@interface PoyntTransactionResponseObject : NSObject
@property (nonatomic, copy) NSString * _Nonnull status;
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic, copy) NSString * _Nonnull currency;
@property (nonatomic, copy) NSString * _Nonnull referenceId;
@property (nonatomic) float tipAmount;
@property (nonatomic) float amount;
@property (nonatomic) BOOL multiTender;
@property (nonatomic) BOOL disableTip;
@property (nonatomic) BOOL disableCash;
@property (nonatomic) BOOL nonReferencedCredit;
@property (nonatomic) BOOL disableDebitCards;
@property (nonatomic) BOOL authzOnly;
@property (nonatomic, copy) NSArray<PoyntTransactionObject *> * _Nonnull transactions;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull order;
@property (nonatomic, strong) id _Nullable rawJson;
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
